namespace Kompeldev.Generator.Deconstruct;

/// <summary>
///     Class which contains constants used in the deconstruct generator.
/// </summary>
internal static class DeconstructConstants
{
    internal const string DeconstructAttributeContent = """
                                             // <auto-generated/>

                                             using System;

                                             namespace Kompeldev.Generator.Deconstruct;

                                             [AttributeUsage(AttributeTargets.Class)]
                                             internal sealed class DeconstructAttribute : Attribute;
                                             """;

    internal const string IgnorePropertyAttributeContent = """
                                                           // <auto-generated/>

                                                           using System;

                                                           namespace Kompeldev.Generator.Deconstruct;

                                                           [AttributeUsage(AttributeTargets.Property)]
                                                           internal sealed class IgnorePropertyAttribute : Attribute;
                                                           """;
}