namespace Kompeldev.Generator.Deconstruct;

internal static class DeconstructConstants
{
    internal const string AttributeContent = """
                                             // <auto-generated/>
                                             namespace Kompeldev.Generator.Deconstruct;
                                             
                                             [System.AttributeUsage(System.AttributeTargets.Class)]
                                             internal sealed class DeconstructAttribute : System.Attribute;
                                             """;
}